### ISSUE TITLE
can't run builder on linux (python 3.7)

### ISSUE THREAD

**Issue by aidenpearce001** [Bitwise-01/Loki#34]
Traceback (most recent call last):
  File "/home/kali/miniconda3/envs/botnet/lib/python3.6/shutil.py", line 550, in move
    os.rename(src, real_dst)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpwhs7xbl7/application/.payload.exe' -> '.bin/.payload.exe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "builder.py", line 159, in <module>
    executor.start()
  File "builder.py", line 124, in start
    self.compile_bot()
  File "builder.py", line 108, in compile_bot
    self.move_file(self.bot_compiled, payload_output)
  File "builder.py", line 121, in move_file
    shutil.move(path, output_dir)
  File "/home/kali/miniconda3/envs/botnet/lib/python3.6/shutil.py", line 564, in move
    copy_function(src, real_dst)
  File "/home/kali/miniconda3/envs/botnet/lib/python3.6/shutil.py", line 263, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/home/kali/miniconda3/envs/botnet/lib/python3.6/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpwhs7xbl7/application/.payload.exe'

**Comment by throwawaya609** [comment]
Did you find any answers?

**Comment by AsyncSan** [comment]
Seems like it cannot find the file '/tmp/tmpwhs7xbl7/application/.payload.exe'
